FROM node:20.19.6-alpine as develop-stage
WORKDIR /app
COPY package*.json ./
RUN npm global add @quasar/cli
COPY . .
# build stage
FROM develop-stage as build-stage
RUN quasar dev
# production stage